name: serinus_swagger
description: A Serinus plugin to generate OpenAPI documentation from your Serinus app.
version: 1.0.4
repository: https://github.com/francescovallone/serinus/tree/main/packages/serinus_swagger
homepage: https://serinus.app/open-api/introduction.html
documentation: https://serinus.app/open-api/introduction.html
tag: 
  - server
  - swagger
  - backend
  - web
  - openapi

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serinus: ^1.0.0
  yaml_writer: ^2.0.0

dev_dependencies:
  lints: ">=3.0.0 <6.0.0"
  test: ^1.24.0
